export const ENV_VARS = {
    MAPBOX_ACCESS: process.env["REACT_APP_MAPBOX_ACCESS_TOKEN"],
    MAPBOX_STYLE: process.env["REACT_APP_MAPBOX_STYLE_URL"],
    INSET_MAPBOX_STYLE: process.env["REACT_APP_INSET_MAP_STYLE_URL"],
    INSET_MAPBOX_ACCESS: process.env["REACT_MAPBOX_INSET_ACCESS_TOKEN"],
    CHANNEL_ID:process.env["REACT_APP_CHANNEL_ID"]
}
